/// One row per Procurement Act tender (a procurement with a UK4 notice), from
/// fct_procurements. Open = Closing Date from today, no award, not cancelled.
table Procurements
	lineageTag: 1d64a086-5142-44d2-99c0-7b983d8db144

	measure Tenders = COUNTROWS(Procurements)
		formatString: #,0
		lineageTag: ff30c2e0-8f86-4d89-a946-5c6820001565

	/// Closing date from today, no award published, not cancelled; ignores the date slicer.
	/// Only tenders closing within the "Closes within" slicer's window (any time when nothing is chosen).
	measure 'Open Tenders' =
			VAR LastClosingDate = TODAY() + [Window Days]
			RETURN
			    CALCULATE(
			        COUNTROWS(Procurements),
			        REMOVEFILTERS('Date'),
			        KEEPFILTERS(Procurements[Closing Date] >= TODAY()),
			        KEEPFILTERS(Procurements[Closing Date] <= LastClosingDate),
			        KEEPFILTERS(Procurements[Award Published Date] = BLANK()),
			        KEEPFILTERS(Procurements[Is Cancelled] = FALSE())
			    )
		formatString: #,0
		displayFolder: Open tenders
		lineageTag: f4a14c49-bf22-4039-8885-27dde8ff43f4

	/// All open tenders, whatever the "Closes within" slicer says
	measure 'All Open Tenders' = CALCULATE([Open Tenders], REMOVEFILTERS('Closing Window')) + 0   // 0, not (Blank), when nothing matches
		formatString: #,0
		displayFolder: Open tenders
		lineageTag: 9d91024b-7967-4597-99b7-68e4bb7b457f

	/// Open tenders closing within the slicer's window; 14 days when nothing is chosen
	measure 'Closing Soon' =
			VAR LastClosingDate = TODAY() + SELECTEDVALUE('Closing Window'[Days], 14)
			RETURN
			    CALCULATE(
			        [Open Tenders],
			        REMOVEFILTERS('Closing Window'),
			        KEEPFILTERS(Procurements[Closing Date] <= LastClosingDate)
			    ) + 0   // 0, not (Blank), when nothing matches
		formatString: #,0
		displayFolder: Open tenders
		lineageTag: 56fd6412-d4ed-43a0-ad73-c29f7e9f1717

	/// Label under Closing Soon, e.g. "Close within 7 days"
	measure 'Closing Soon Label' =
			VAR WindowDays = SELECTEDVALUE('Closing Window'[Days], 14)
			RETURN
			    SWITCH(
			        TRUE(),
			        WindowDays = 0, "Close today",
			        WindowDays >= 36500, "Open, any closing date",
			        "Close within " & WindowDays & " days"
			    )
		displayFolder: Open tenders
		lineageTag: a67e081f-249e-4648-a2e6-59822989e2b7

	/// Blank unless open, so tables show open tenders only
	/// Shown as Today, 1 day or n days; still a number, so tables sort by it
	measure 'Days to Close' = IF([Open Tenders] > 0, INT(MAX(Procurements[Closing Date]) - TODAY()))
		displayFolder: Open tenders
		lineageTag: 113d80a2-7f0c-444b-a099-99ebc925ca82

		formatStringDefinition = SWITCH(SELECTEDMEASURE(), 0, """Today""", 1, """1 day""", "0 ""days""")

	/// Timings are dated by award: date filters and axes apply to the award date, not the tender date.
	/// Only tenders whose days to award fall in the "Days waited" range (table Wait Days)
	measure 'Median Days Tender to Award' =
			CALCULATE(
			    MEDIAN(Procurements[Days Tender to Award]),
			    USERELATIONSHIP(Procurements[Award Published Date], 'Date'[Date]),
			    KEEPFILTERS(TREATAS(VALUES('Wait Days'[Days]), Procurements[Days Tender to Award]))
			)
		formatString: 0
		displayFolder: Timings
		lineageTag: 88b20e99-956c-48a4-90e3-f7cfa7bb0bdb

	/// Only awards at least 3 months old: contracts for newer awards are often not published yet, so
	/// counting them would leave only the quick ones and make the wait look shorter than it is.
	/// Only awards whose days to contract fall in the "Days waited" range (table Wait Days)
	measure 'Median Days Award to Contract' =
			CALCULATE(
			    MEDIAN(Procurements[Days Award to Contract]),
			    USERELATIONSHIP(Procurements[Award Published Date], 'Date'[Date]),
			    KEEPFILTERS(Procurements[Award Published Date] <= TODAY() - 91),
			    KEEPFILTERS(TREATAS(VALUES('Wait Days'[Days]), Procurements[Days Award to Contract]))
			)
		formatString: 0
		displayFolder: Timings
		lineageTag: 23b78e08-8560-453b-93cf-79a79e7efce1

	/// Tenders with an award published, dated by the award. Only tenders whose days to award fall
	/// in the "Days waited" range (table Wait Days; every awarded tender has days to award)
	measure 'Tenders Awarded' =
			CALCULATE(
			    COUNTROWS(Procurements),
			    USERELATIONSHIP(Procurements[Award Published Date], 'Date'[Date]),
			    KEEPFILTERS(NOT ISBLANK(Procurements[Award Published Date])),
			    KEEPFILTERS(TREATAS(VALUES('Wait Days'[Days]), Procurements[Days Tender to Award]))
			)
		formatString: #,0
		displayFolder: Timings
		lineageTag: 7b92cdb9-161f-4648-bb09-19728a5a4db1

	/// Tenders Timed whose days for the chosen stage fall in the band on the axis (table Wait Band)
	measure 'Tenders in Wait Band' =
			VAR FromDays = SELECTEDVALUE('Wait Band'[From Days])
			VAR ToDays = SELECTEDVALUE('Wait Band'[To Days])
			VAR StageName = SELECTEDVALUE(Stage[Stage], "Tender to award")
			RETURN
			    IF(
			        StageName = "Award to contract",
			        CALCULATE(
			            [Tenders Timed],
			            KEEPFILTERS(Procurements[Days Award to Contract] >= FromDays),
			            KEEPFILTERS(Procurements[Days Award to Contract] <= ToDays)
			        ),
			        CALCULATE(
			            [Tenders Timed],
			            KEEPFILTERS(Procurements[Days Tender to Award] >= FromDays),
			            KEEPFILTERS(Procurements[Days Tender to Award] <= ToDays)
			        )
			    )
		formatString: #,0
		displayFolder: Timings
		lineageTag: f55e7eec-5bad-44da-b616-6e41b09aad1a

	/// Share of Tenders Timed that fall in the band; the bands add up to 100%
	measure 'Share in Wait Band' = DIVIDE([Tenders in Wait Band], [Tenders Timed])
		formatString: 0%
		displayFolder: Timings
		lineageTag: 4e3d4cde-4be0-4dc4-8fff-58df548aa2cf

	/// Share in Wait Band per legend group (table Colour Group), each group adding up to 100%:
	/// Digital and data / Other markets when no market is chosen, otherwise one per chosen market
	measure 'Share in Wait Band by Group' =
			VAR GroupName = SELECTEDVALUE('Colour Group'[Group])
			// colour by market once a Market, Sector or Buyer slicer is used (as Awarded Value by Group)
			VAR MarketChosen =
			    ISFILTERED(Sector[Market]) || ISFILTERED(Sector[Sector]) || ISFILTERED(Buyer[Buyer])
			RETURN
			    SWITCH(
			        TRUE(),
			        NOT MarketChosen && GroupName = "Digital and data",
			            CALCULATE([Share in Wait Band], KEEPFILTERS(Sector[Market] = "Digital and data")),
			        NOT MarketChosen && GroupName = "Other markets",
			            CALCULATE([Share in Wait Band], KEEPFILTERS(Sector[Market] <> "Digital and data")),
			        NOT MarketChosen || GroupName = "Other markets", BLANK(),
			        CALCULATE([Share in Wait Band], KEEPFILTERS(Sector[Market] = GroupName))
			    )
		formatString: 0%
		displayFolder: Timings
		lineageTag: d3632ee1-d539-4906-bea9-6b48c079ff5d

	/// Footnote on How long to award?: the months the page covers and how the numbers are counted
	measure 'Timing Note' =
			VAR Period = FORMAT(MIN('Date'[Date]), "mmm yyyy") & " to " & FORMAT(MAX('Date'[Date]), "mmm yyyy")
			RETURN
			    "Tenders awarded " & Period & ", in calendar days between notices; only tenders that reached an award count, "
			        & "so slower ones still waiting are missing. Earlier months are left out: the Act began in Feb 2025, so they'd "
			        & "look falsely fast. Award to contract counts awards at least 3 months old. Cards show medians."
		displayFolder: Timings
		lineageTag: fb71fee9-7f93-4240-9770-509e41b60f5f

	/// Days for the stage chosen in the Stage slicer (tender to award when none is chosen):
	/// a tender's own days in a table row, the median elsewhere
	measure 'Days for Stage' =
			VAR StageName = SELECTEDVALUE(Stage[Stage], "Tender to award")
			RETURN
			    IF(StageName = "Award to contract", [Median Days Award to Contract], [Median Days Tender to Award])
		formatString: 0
		displayFolder: Timings
		lineageTag: a14d73aa-c309-450a-9758-20b27647a011

	/// Tenders awarded with days known for the chosen stage; for award to contract, only awards
	/// at least 3 months old, as in Median Days Award to Contract. Only tenders whose days for the
	/// stage fall in the "Days waited" range (table Wait Days); award to contract is counted here
	/// rather than from Tenders Awarded, which follows the range by days to award
	measure 'Tenders Timed' =
			VAR StageName = SELECTEDVALUE(Stage[Stage], "Tender to award")
			RETURN
			    IF(
			        StageName = "Award to contract",
			        CALCULATE(
			            COUNTROWS(Procurements),
			            USERELATIONSHIP(Procurements[Award Published Date], 'Date'[Date]),
			            KEEPFILTERS(Procurements[Award Published Date] <= TODAY() - 91),
			            KEEPFILTERS(TREATAS(VALUES('Wait Days'[Days]), Procurements[Days Award to Contract]))
			        ),
			        [Tenders Awarded]
			    )
		formatString: #,0
		displayFolder: Timings
		lineageTag: f7be6073-24b3-480b-9e06-b846dc066bb3

	/// The table's days column: each tender's days for the chosen stage. Clicking a bar in the wait
	/// chart filters the disconnected Wait Band and Colour Group tables, so only tenders in that band
	/// (and that bar's market group) keep a value and the table lists just them. Days for Stage
	/// already follows the "Days waited" slider
	measure 'Days in Chosen Band' =
			VAR FromDays = MIN('Wait Band'[From Days])
			VAR ToDays = MAX('Wait Band'[To Days])
			VAR GroupName = SELECTEDVALUE('Colour Group'[Group])
			VAR Days =
			    SWITCH(
			        TRUE(),
			        ISBLANK(GroupName), [Days for Stage],
			        GroupName = "Digital and data", CALCULATE([Days for Stage], KEEPFILTERS(Sector[Market] = "Digital and data")),
			        GroupName = "Other markets", CALCULATE([Days for Stage], KEEPFILTERS(Sector[Market] <> "Digital and data")),
			        CALCULATE([Days for Stage], KEEPFILTERS(Sector[Market] = GroupName))
			    )
			RETURN
			    IF(NOT ISBLANK(Days) && Days >= FromDays && Days <= ToDays, Days)
		formatString: 0
		displayFolder: Timings
		lineageTag: fdab407a-8756-45c0-8ccf-ec068ed24bd6

	/// Takeaway under the wait chart, following the Stage switch and the filters
	measure 'Wait Chart Story' =
			VAR StageName = SELECTEDVALUE(Stage[Stage], "Tender to award")
			VAR Timed = [Tenders Timed]
			VAR Quick =
			    // 0 rather than blank when none are quick, so the line reads "0% of ..."
			    COALESCE(
			        IF(
			            StageName = "Award to contract",
			            CALCULATE([Tenders Timed], KEEPFILTERS(Procurements[Days Award to Contract] <= 90)),
			            CALCULATE([Tenders Timed], KEEPFILTERS(Procurements[Days Tender to Award] <= 180))
			        ),
			        0
			    )
			RETURN
			    SWITCH(
			        TRUE(),
			        ISBLANK(Timed), "No tenders match these filters.",
			        // the Days waited slider can leave all or none of them quick
			        Quick = Timed && StageName = "Award to contract", "All of these contracts follow within 3 months of the award.",
			        Quick = Timed, "All of these tenders are awarded within 6 months.",
			        Quick = 0 && StageName = "Award to contract", "None of these contracts follow within 3 months of the award.",
			        Quick = 0, "None of these tenders are awarded within 6 months.",
			        StageName = "Award to contract",
			            FORMAT(DIVIDE(Quick, Timed), "0%") & " of contracts follow within 3 months of the award.",
			        FORMAT(DIVIDE(Quick, Timed), "0%") & " of tenders are awarded within 6 months; the rest take longer."
			    )
		displayFolder: Timings
		lineageTag: 8c7e661a-ac60-4374-b526-3392c63d1e6b

	/// Chart and table titles that follow the Stage slicer
	measure 'Wait Chart Title' =
			VAR StageName = SELECTEDVALUE(Stage[Stage], "Tender to award")
			RETURN
			    IF(StageName = "Award to contract", "How long from award to contract", "How long tenders wait for an award")
		displayFolder: Timings
		lineageTag: 57581cff-b747-4544-b836-cfddcd8e0528

	/// The table's title, with how many tenders it lists, so it visibly follows the Days waited
	/// slider and a click on the chart (dated by award, like the table's days)
	measure 'Wait Table Title' =
			VAR StageName = SELECTEDVALUE(Stage[Stage], "Tender to award")
			VAR Listed =
			    COUNTROWS(
			        FILTER(
			            CALCULATETABLE(
			                VALUES(Procurements[OCID]),
			                USERELATIONSHIP(Procurements[Award Published Date], 'Date'[Date])
			            ),
			            NOT ISBLANK([Days in Chosen Band])
			        )
			    )
			VAR ListedText = FORMAT(Listed, "#,0")
			RETURN
			    SWITCH(
			        TRUE(),
			        ISBLANK(Listed), "No tenders match these filters",
			        StageName = "Award to contract",
			            ListedText & IF(Listed = 1, " award", " awards") & " by wait for a contract, longest first",
			        ListedText & IF(Listed = 1, " tender", " tenders") & " by wait for an award, longest first"
			    )
		displayFolder: Timings
		lineageTag: 73ca0d5f-5077-4d42-94ea-6563f4a2294a

	/// Estimated value incl. VAT of an open tender, from its latest tender notice (blank when not open).
	/// Framework values are spending caps and show as "£… (cap)"; never add these up
	measure 'Tender Value' = IF([Open Tenders] > 0, SUM(Procurements[Tender Value GBP]))
		displayFolder: Open tenders
		lineageTag: b067f0b5-4c92-47bb-9dde-1b5f4d7cf3e1

		formatStringDefinition = IF(CALCULATE(COUNTROWS(Procurements), KEEPFILTERS(Procurements[Is Framework] = TRUE())) > 0, "£#,0"" (cap)""", "£#,0")

	/// Open tenders first published in the last 7 days, whatever the "Closes within" slicer says
	measure 'New This Week' =
			CALCULATE(
			    [Open Tenders],
			    REMOVEFILTERS('Closing Window'),
			    KEEPFILTERS(Procurements[Tender Published Date] >= TODAY() - 7)
			) + 0   // 0, not (Blank), when nothing matches
		formatString: #,0
		displayFolder: Open tenders
		lineageTag: a13ecf11-6d10-44fd-be1f-5bb5c283b65f

	column OCID
		dataType: string
		isKey
		lineageTag: 8112226c-942f-40bb-a31d-15a0b7fadab8
		summarizeBy: none
		sourceColumn: OCID

	column Title
		dataType: string
		lineageTag: 9f111f73-f0f1-4255-8241-13ac40c2867f
		summarizeBy: none
		sourceColumn: TITLE

	column 'Buyer Key'
		dataType: string
		isHidden
		lineageTag: 8766d470-560a-4369-9048-78d5ee4c0dc0
		summarizeBy: none
		sourceColumn: BUYER_KEY

	column 'CPV Division'
		dataType: string
		isHidden
		lineageTag: fa304be0-68bd-4b49-8346-71c139f53096
		summarizeBy: none
		sourceColumn: CPV_DIVISION

	column 'Tender Published Date'
		dataType: dateTime
		formatString: dd mmm yyyy
		lineageTag: 576799ee-76a5-4d80-aa04-9482e9961fd6
		summarizeBy: none
		sourceColumn: TENDER_PUBLISHED_DATE

		annotation UnderlyingDateTimeDataType = Date

	column 'Closing Date'
		dataType: dateTime
		formatString: dd mmm yyyy
		lineageTag: 938a993f-2162-4a13-8c83-5753160c79d1
		summarizeBy: none
		sourceColumn: CLOSING_DATE

		annotation UnderlyingDateTimeDataType = Date

	column 'Award Published Date'
		dataType: dateTime
		formatString: dd mmm yyyy
		lineageTag: 6c6616c5-9660-4705-802b-48e896b86589
		summarizeBy: none
		sourceColumn: AWARD_PUBLISHED_DATE

		annotation UnderlyingDateTimeDataType = Date

	column 'Contract Published Date'
		dataType: dateTime
		formatString: dd mmm yyyy
		lineageTag: 605a46c1-e505-4b70-ac7e-49cf5fe87f66
		summarizeBy: none
		sourceColumn: CONTRACT_PUBLISHED_DATE

		annotation UnderlyingDateTimeDataType = Date

	column 'Days Tender to Award'
		dataType: double
		formatString: 0
		lineageTag: 5c84fc82-3b7f-458d-b664-4b9367c70ada
		summarizeBy: sum
		sourceColumn: DAYS_TENDER_TO_AWARD

		annotation SummarizationSetBy = Automatic

	column 'Days Award to Contract'
		dataType: double
		formatString: 0
		lineageTag: 86b3b6a3-c019-4398-8e4a-cfcd4769aa16
		summarizeBy: sum
		sourceColumn: DAYS_AWARD_TO_CONTRACT

		annotation SummarizationSetBy = Automatic

	column 'Is Cancelled'
		dataType: boolean
		lineageTag: 99569fd8-c9d6-4aeb-9ab0-0f08af88cf99
		summarizeBy: none
		sourceColumn: IS_CANCELLED

	/// Link to the latest tender notice on Find a Tender
	column Notice
		dataType: string
		lineageTag: ca4444b2-7307-47f1-bef7-8ab8db9e028a
		dataCategory: WebUrl
		summarizeBy: none
		sourceColumn: TENDER_NOTICE_URL

	column 'Tender Value GBP'
		dataType: double
		isHidden
		formatString: £#,0
		lineageTag: 7b287e20-5df2-4ba5-ac43-dcfae354f7bf
		summarizeBy: none
		sourceColumn: TENDER_VALUE_GBP

	column 'Is Framework'
		dataType: boolean
		isHidden
		lineageTag: 97412547-daf5-4856-b24d-92526bb547b6
		summarizeBy: none
		sourceColumn: IS_FRAMEWORK

	/// "SME-friendly only" when at least one lot is marked suitable for SMEs, else "Other"; for the tick box on What's open to bid?
	column 'Suitable for SMEs'
		dataType: string
		lineageTag: 0489fff1-8c10-423b-90fb-503fd9f734b2
		summarizeBy: none
		sourceColumn: SUITABLE_FOR_SMES

	column 'Tender Notice ID'
		dataType: string
		isHidden
		lineageTag: 6f5cce53-f64b-4708-bb8e-6fd9b1c6daf5
		summarizeBy: none
		sourceColumn: TENDER_NOTICE_ID

		annotation SummarizationSetBy = Automatic

	column 'Is Suitable For SME'
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 7a2416fb-34b2-41b1-bb6f-e079e7e3e331
		summarizeBy: none
		sourceColumn: IS_SUITABLE_FOR_SME

		annotation SummarizationSetBy = Automatic

	partition Procurements = m
		mode: import
		source =
				let
				    Source = Marts{[Name = "FCT_PROCUREMENTS", Kind = "Table"]}[Data],
				    // the slicer shows one tick box, "SME-friendly only"
				    WithSmes = Table.AddColumn(Source, "SUITABLE_FOR_SMES", each if [IS_SUITABLE_FOR_SME] then "SME-friendly only" else "Other", type text)
				in
				    WithSmes

	annotation PBI_ResultType = Table

