-- Role for dbt: reads the raw tables and builds its own schemas (STAGING, MARTS, ...).
-- Needs ACCOUNTADMIN for the grants. Run after 01 and 02.
USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS TENDER_TRANSFORM;
GRANT ROLE TENDER_TRANSFORM TO ROLE SYSADMIN;   -- admins can use and manage its objects

GRANT USAGE ON DATABASE TENDER_DB TO ROLE TENDER_TRANSFORM;
GRANT USAGE ON WAREHOUSE TENDER_WH TO ROLE TENDER_TRANSFORM;
GRANT CREATE SCHEMA ON DATABASE TENDER_DB TO ROLE TENDER_TRANSFORM;   -- dbt creates its schemas

-- Read-only access to the raw data
GRANT USAGE ON SCHEMA TENDER_DB.RAW TO ROLE TENDER_TRANSFORM;
GRANT SELECT ON TABLE TENDER_DB.RAW.FIND_A_TENDER_RELEASES TO ROLE TENDER_TRANSFORM;
GRANT SELECT ON TABLE TENDER_DB.RAW.FIND_A_TENDER_INGEST_RUNS TO ROLE TENDER_TRANSFORM;

-- Developers run dbt with this role; replace with your user name
GRANT ROLE TENDER_TRANSFORM TO USER JACEKJ;
